dist: xenial

matrix:
  include:
    - python:  3.6
      env:  NUMPY=1.15.4


before_install:
   - uname -a
   - df -h
   - ulimit -a

    - pip uninstall --yes numpy
    - python -m pip install --upgrade pip
    - sudo apt-get install -y autodock-vina


install:
    - pip install -r requirements.txt

script:
    - python regression-test.py

    # Run checks
  - flake8
  - mypy

after_success:
    # Upload coverage report to codecov
  #- codecov

notifications:
    email: false

